import { getLessonById, lessons, difficulties } from "@/data/lessons";
import { notFound } from "next/navigation";
import LessonContent from "@/components/LessonContent";
import { Metadata } from "next";
import { BookOpen } from "lucide-react";
import { Card, CardHeader, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

/*
 * DO NOT EDIT THIS FILE
 *
 * This is the page for the lesson.
 * It is a dynamic route that will be used to display the lesson content.
 */

export async function generateMetadata({
  params,
}: {
  params: { lessonId: string };
}): Promise<Metadata> {
  "use cache";
  const param = await params;
  const lesson = getLessonById(param.lessonId);
  if (!lesson) return {};
  return {
    title: `${lesson.title} | Your Course Name`,
    description: lesson.description,
  };
}

export default async function LessonPage({
  params,
}: {
  params: { lessonId: string };
}) {
  const param = await params;
  const lesson = getLessonById(param.lessonId);

  if (!lesson) {
    notFound();
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8">
        <Card className="max-w-4xl mx-auto">
          <CardHeader className="space-y-4">
            <h1 className="text-3xl font-bold">{lesson.title}</h1>
            <p className="text-muted-foreground">{lesson.description}</p>
            <div className="flex flex-wrap gap-4">
              <Badge variant="secondary" className="flex items-center gap-1">
                <BookOpen className="w-4 h-4" />
                {difficulties[lesson.difficulty]}
              </Badge>
              <Badge variant="outline">{lesson.category}</Badge>
            </div>
          </CardHeader>

          <CardContent>
            <LessonContent lessonId={lesson.id} />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// This ensures pages are statically generated at build time
export function generateStaticParams() {
  return lessons.map((lesson) => ({
    lessonId: lesson.id,
  }));
}
